Add a hidden debug tool to gssproxy
gssapi/gssproxy pull request #15
Opened 2020-09-03 19:44 UTC by simo5

Sometimes it is really valuable to be able to extract the ccaches that a
client may be storing encrypted.

This special tool allows that and can be used as follow:

KRB5CCNAME=~/decryptedccache KRB5_KTNAME=/path/to/service.keytab ./gssproxy -d --extract-ccache /path/to/encrypted.ccache

Then using a file ccache as the default ccache, the ccache must be
initialized first with something like kinit and then the decrypted
contents will be appended to it. It doesn't matter what creedntials are
used for the kinit part.

2020-09-03 19:45 UTC, simo5 commented
I really needed this to debug an issue I found.
So might as well commit it, it is a hidden feature, but may come handy to debug stuff in a pinch.

2020-09-09 21:17 UTC, frozencemetery requested changes
Typo in commit message - "creedntials".

A couple changes are requested inline, along with some suggestions.

2020-09-10 17:50 UTC, simo5 commented on src/gssproxy.c
> +        return extract_ccache(opt_extract_ccache);
ok

2020-09-10 17:51 UTC, simo5 commented on src/extract_ccache.c
> +    struct gp_creds_handle *handle;
ack

2020-09-10 17:53 UTC, simo5 commented on src/extract_ccache.c
> +#define ENC_MIN_PAD_LEN 8
ok moving defs to gp_common.h

2020-09-10 17:54 UTC, simo5 commented on src/extract_ccache.c
> +    int i, j;
ok

2020-09-10 17:56 UTC, simo5 commented on src/extract_ccache.c
> +        }
We can't do it this way, we need to walk backwards from the end of the packet to find where the padding stops.

2020-09-10 17:57 UTC, simo5 commented on src/extract_ccache.c
> +        }
Actually, I'll take that back, I see how we can do it, I'll try to get to something reasonable :-)

2020-09-10 18:16 UTC, simo5 commented on src/extract_ccache.c
> +    i = data_out.length - 1;
yeah, done

2020-09-10 20:05 UTC, frozencemetery commented
@simo5, I see changes marked resolved but no revision - missing push?

2020-09-10 20:24 UTC, simo5 commented
Yeah sorry, I was interrupted between testing the changes and pushing, will fix ASAP

2020-09-10 20:58 UTC, simo5 commented
Ok I figured out also why the tool would not initialize a ccache if it does not exist already, so I added a new option --into-ccache that triggers the right behaviour.
I should have done this from the start as it is very unlikely an admin would want to decrypt a ccache into their own default one anyway, and this is easier to use than setting environment variables anyway

2020-09-10 21:13 UTC, frozencemetery approved these changes

2020-09-10 21:13 UTC, merged